### ISSUE TITLE
README notes

### ISSUE THREAD

**Issue by aniwarp** [doctordns/ReskitBuildScripts#1]
Sadly, this took an embarrassingly amount of time to figure out. However, to help future people with using your lab scripts, I'd like to suggest the following to be placed in your README file.

Putting a quick note to input servers from your hosts.txt in the hosts file on the HV host.

Making sure the Internal HV network category is labeled as Private and not Public. Just had to use Get-NetConnectionProfile and Set-NetconnectionProfile.

Putting the host IP 10.10.10.252 on the internal network NIC.

Again, nothing difficult, but it wasn't exceedingly obvious coming from Linux-land either. Once I did the above, your scripts worked great!

**Comment by doctordns** [comment]
First - for some reason I never saw this so apologies for not getting onto it earlier!

I agree with all the comments. 

I have creates a new release of the scripts that create Gen 2 VMs. I have also updated the readme file to reflect your comments.

Please take a look and let me know what else I can add. 
And feel free to fork this repo and make any suggested edits you feel will add value.

**Comment by doctordns** [comment]
I think this is fixed>!
