### ISSUE TITLE
Error Chapter 1 Step #7

### ISSUE THREAD

**Issue by dbad67** [doctordns/ReskitBuildScripts#2]
Get-Childitem -Path $env:ProgramFiles\PowerShell\7 -Recurse |  Measure-Object -Property Length -Sum

Returns Error - See attached
![Chap 1 Step 7 error](https://user-images.githubusercontent.com/109050899/178174896-7bf143b2-14b4-4c62-9dec-10066a695201.png)

Successfully used the following:
Get-Childitem -Path C:\Users\Administrator\AppData\Local\Microsoft\powershell -Recurse | Measure-Object -Property Length -Sum

**Comment by doctordns** [comment]
I suspect that is because you have used either winget or the store to install PowerSHell.
